services:
  harvey:
    build:
      context: .
    volumes:
      - ./data:/data
    labels:
      caddy: ":80"
      caddy.reverse_proxy: "harvey:8080"
      caddy.reverse_proxy.lb_retries: "1000"

  harvey-replica:
    build:
      context: .
    volumes:
      - ./data:/data
    labels:
      caddy: ":80"
      caddy.reverse_proxy: "harvey-replica:8080"
      caddy.reverse_proxy.lb_retries: "1000"

  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.9
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
